"""
Tests for RAPTOR module.

Run with:
    poetry run pytest tests/modules/test_raptor.py -v
"""

import pytest
from unittest.mock import AsyncMock, MagicMock
from typing import List

from langchain_core.documents import Document

from tilellm.modules.raptor.models.models import (
    RaptorTree,
    RaptorNode,
    RaptorLevel,
    RaptorConfig,
    RaptorRetrievalStrategy,
    RaptorRequest,
    RaptorRetrievalRequest,
)
from tilellm.modules.raptor.config_loader import (
    is_raptor_enabled,
    should_use_raptor_for_document,
    get_raptor_config_from_env,
)
from tilellm.modules.raptor.repository import RaptorRepository
from tilellm.modules.raptor.services.raptor_service import RaptorService
from tilellm.modules.raptor.services.retrieval_strategies import RaptorRetriever


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def sample_chunks() -> List[Document]:
    """Create sample document chunks for testing."""
    return [
        Document(
            page_content=f"Content of chunk {i}. This is important information about topic {i % 3}.",
            metadata={
                "id": f"chunk_{i}",
                "doc_id": "test_doc",
                "namespace": "test-namespace",
                "page": i // 5,
                "source": "test.pdf",
            }
        )
        for i in range(25)
    ]


@pytest.fixture
def mock_llm():
    """Create a mock LLM."""
    llm = AsyncMock()
    llm.model_name = "test-model"
    
    # Mock ainvoke to return summary
    async def mock_ainvoke(prompt):
        response = MagicMock()
        response.content = f"Summary of the provided content. Generated by {llm.model_name}."
        return response
    
    llm.ainvoke = mock_ainvoke
    return llm


@pytest.fixture
def mock_embeddings():
    """Create mock embeddings model."""
    embeddings = MagicMock()
    
    def mock_embed_query(text):
        return [0.1] * 1536  # Return dummy embedding
    
    def mock_embed_documents(texts):
        return [[0.1] * 1536 for _ in texts]
    
    embeddings.embed_query = mock_embed_query
    embeddings.embed_documents = mock_embed_documents
    return embeddings


@pytest.fixture
def mock_sparse_encoder():
    """Create mock sparse encoder."""
    encoder = MagicMock()
    
    def mock_encode_queries(text):
        # Return dummy sparse vector
        return {"indices": [1, 5, 10], "values": [0.8, 0.5, 0.3]}
    
    encoder.encode_queries = mock_encode_queries
    return encoder


@pytest.fixture
def mock_vector_repo_with_hybrid():
    """Create mock vector store repository with hybrid support."""
    repo = AsyncMock()
    
    async def mock_add_item(item_data):
        # Verify sparse embeddings if present
        if "sparse_embeddings" in item_data:
            assert len(item_data["sparse_embeddings"]) == len(item_data["embeddings"])
        return True
    
    async def mock_similarity_search_with_score(namespace, query_embedding, k, filter=None):
        results = []
        for i in range(min(k, 5)):
            doc = Document(
                page_content=f"Result {i}",
                metadata={"id": f"result_{i}", "level": 0, "has_sparse": True}
            )
            results.append((doc, 0.9 - i * 0.1))
        return results
    
    repo.add_item = mock_add_item
    repo.similarity_search_with_score = mock_similarity_search_with_score
    return repo


@pytest.fixture
def mock_redis():
    """Create mock Redis client."""
    redis = AsyncMock()
    redis.get = AsyncMock(return_value=None)
    redis.set = AsyncMock(return_value=True)
    redis.hset = AsyncMock(return_value=True)
    redis.hgetall = AsyncMock(return_value={})
    redis.delete = AsyncMock(return_value=True)
    redis.keys = AsyncMock(return_value=[])
    return redis


# ---------------------------------------------------------------------------
# Test Configuration
# ---------------------------------------------------------------------------

class TestConfigLoader:
    """Test configuration loading."""
    
    def test_is_raptor_enabled_false_by_default(self, monkeypatch):
        """Test RAPTOR is disabled by default."""
        monkeypatch.setenv("ENABLE_RAPTOR", "false")
        assert not is_raptor_enabled()
    
    def test_is_raptor_enabled_true(self, monkeypatch):
        """Test RAPTOR can be enabled."""
        monkeypatch.setenv("ENABLE_RAPTOR", "true")
        assert is_raptor_enabled()
    
    def test_should_use_raptor_for_document_type(self, monkeypatch):
        """Test document type activation."""
        monkeypatch.setenv("ENABLE_RAPTOR", "true")
        monkeypatch.setenv("RAPTOR_ENABLED_DOC_TYPES", "accademico,tecnico")
        
        assert should_use_raptor_for_document(doc_type="accademico")
        assert should_use_raptor_for_document(doc_type="tecnico")
        assert not should_use_raptor_for_document(doc_type="generico")
    
    def test_should_use_raptor_for_page_count(self, monkeypatch):
        """Test page count activation."""
        monkeypatch.setenv("ENABLE_RAPTOR", "true")
        monkeypatch.setenv("RAPTOR_MIN_PAGES", "10")
        
        assert should_use_raptor_for_document(page_count=15)
        assert not should_use_raptor_for_document(page_count=5)
    
    def test_get_raptor_config_from_env(self, monkeypatch):
        """Test configuration from environment."""
        monkeypatch.setenv("RAPTOR_CLUSTER_SIZE", "7")
        monkeypatch.setenv("RAPTOR_MAX_LEVELS", "2")
        monkeypatch.setenv("RAPTOR_MIN_PAGES", "15")
        
        config = get_raptor_config_from_env()
        
        assert config.cluster_size == 7
        assert config.max_levels == 2
        assert config.min_pages_for_raptor == 15


# ---------------------------------------------------------------------------
# Test Models
# ---------------------------------------------------------------------------

class TestModels:
    """Test Pydantic models."""
    
    def test_raptor_config_default(self):
        """Test RaptorConfig defaults."""
        config = RaptorConfig()
        
        assert config.cluster_size == 5
        assert config.max_levels == 3
        assert config.min_pages_for_raptor == 10
        assert config.retrieval_strategy == RaptorRetrievalStrategy.COLLAPSED_TREE
    
    def test_raptor_node_creation(self):
        """Test RaptorNode creation."""
        node = RaptorNode(
            node_id="test_node",
            level=RaptorLevel.LEVEL_0,
            content="Test content",
            metadata={"doc_id": "test_doc"},
        )
        
        assert node.node_id == "test_node"
        assert node.level == RaptorLevel.LEVEL_0
        assert node.content == "Test content"
        assert node.child_ids == []
        assert node.parent_id is None
    
    def test_raptor_tree_creation(self, sample_chunks):
        """Test RaptorTree creation."""
        tree = RaptorTree(
            tree_id="test_tree",
            namespace="test-ns",
            doc_id="test_doc",
            leaf_ids=["chunk_1", "chunk_2"],
            root_ids=["summary_1"],
            levels={0: ["chunk_1", "chunk_2"], 1: ["summary_1"]},
        )
        
        assert tree.tree_id == "test_tree"
        assert tree.namespace == "test-ns"
        assert tree.doc_id == "test_doc"
        assert tree.total_nodes == 0  # Will be updated when nodes are added
    
    def test_raptor_request(self):
        """Test RaptorRequest."""
        request = RaptorRequest(
            namespace="test-ns",
            doc_id="test_doc",
            config=RaptorConfig(cluster_size=7),
        )
        
        assert request.namespace == "test-ns"
        assert request.doc_id == "test_doc"
        assert request.config.cluster_size == 7
    
    def test_raptor_retrieval_request(self):
        """Test RaptorRetrievalRequest."""
        request = RaptorRetrievalRequest(
            question="What is this about?",
            namespace="test-ns",
            strategy=RaptorRetrievalStrategy.TREE_TRAVERSAL,
            top_k=5,
        )
        
        assert request.question == "What is this about?"
        assert request.strategy == RaptorRetrievalStrategy.TREE_TRAVERSAL
        assert request.top_k == 5


# ---------------------------------------------------------------------------
# Test Repository
# ---------------------------------------------------------------------------

class TestRepository:
    """Test RaptorRepository."""
    
    @pytest.mark.asyncio
    async def test_save_tree(self, mock_redis):
        """Test saving tree to Redis."""
        repo = RaptorRepository(redis_client=mock_redis)
        
        tree = RaptorTree(
            tree_id="test_tree",
            namespace="test-ns",
            doc_id="test_doc",
        )
        
        result = await repo.save_tree(tree)
        
        assert result is True
        mock_redis.set.assert_called_once()
    
    @pytest.mark.asyncio
    async def test_get_tree_not_found(self, mock_redis):
        """Test getting non-existent tree."""
        repo = RaptorRepository(redis_client=mock_redis)
        
        tree = await repo.get_tree("non_existent")
        
        assert tree is None
    
    @pytest.mark.asyncio
    async def test_get_summary_namespace(self, mock_redis):
        """Test summary namespace generation."""
        repo = RaptorRepository(redis_client=mock_redis)
        
        namespace = await repo.get_summary_namespace("test-ns")
        
        assert namespace == "test-ns_summaries"


# ---------------------------------------------------------------------------
# Test Service
# ---------------------------------------------------------------------------

class TestRaptorService:
    """Test RaptorService."""
    
    @pytest.mark.asyncio
    async def test_build_raptor_tree(
        self,
        sample_chunks,
        mock_llm,
        mock_embeddings,
        mock_vector_repo,
        mock_redis,
    ):
        """Test building RAPTOR tree."""
        repo = RaptorRepository(redis_client=mock_redis)
        service = RaptorService(repo=repo)
        
        config = RaptorConfig(
            cluster_size=5,
            max_levels=2,
        )
        
        response = await service.build_raptor_tree(
            chunks=sample_chunks,
            namespace="test-ns",
            doc_id="test_doc",
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
            config=config,
        )
        
        assert response.success is True
        assert response.tree_id is not None
        assert response.total_chunks == len(sample_chunks)
        assert response.levels_created >= 1
        assert response.total_summaries > 0
    
    @pytest.mark.asyncio
    async def test_build_raptor_tree_not_enough_chunks(
        self,
        mock_llm,
        mock_embeddings,
        mock_vector_repo,
        mock_redis,
    ):
        """Test building tree with insufficient chunks."""
        repo = RaptorRepository(redis_client=mock_redis)
        service = RaptorService(repo=repo)
        
        few_chunks = [
            Document(page_content="Chunk 1", metadata={"id": "c1"}),
            Document(page_content="Chunk 2", metadata={"id": "c2"}),
        ]
        
        config = RaptorConfig(cluster_size=5)
        
        response = await service.build_raptor_tree(
            chunks=few_chunks,
            namespace="test-ns",
            doc_id="test_doc",
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
            config=config,
        )
        
        assert response.success is False
        assert "Not enough chunks" in response.error


# ---------------------------------------------------------------------------
# Test Retrieval Strategies
# ---------------------------------------------------------------------------

class TestRetrievalStrategies:
    """Test retrieval strategies."""
    
    @pytest.mark.asyncio
    async def test_collapsed_tree_retrieval(
        self,
        mock_embeddings,
        mock_vector_repo,
        mock_redis,
    ):
        """Test collapsed tree retrieval."""
        repo = RaptorRepository(redis_client=mock_redis)
        retriever = RaptorRetriever(repo=repo)
        
        request = RaptorRetrievalRequest(
            question="What is this about?",
            namespace="test-ns",
            strategy=RaptorRetrievalStrategy.COLLAPSED_TREE,
            top_k=5,
        )
        
        mock_llm = AsyncMock()
        
        result = await retriever.retrieve(
            request=request,
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
        )
        
        assert result.success is True
        assert result.strategy_used == "collapsed_tree"
    
    @pytest.mark.asyncio
    async def test_tree_traversal_retrieval(
        self,
        mock_embeddings,
        mock_vector_repo,
        mock_redis,
    ):
        """Test tree traversal retrieval."""
        repo = RaptorRepository(redis_client=mock_redis)
        retriever = RaptorRetriever(repo=repo)
        
        request = RaptorRetrievalRequest(
            question="What are the main themes?",
            namespace="test-ns",
            strategy=RaptorRetrievalStrategy.TREE_TRAVERSAL,
            top_k=5,
        )
        
        # Mock LLM with structured output
        mock_llm = AsyncMock()
        mock_structured_llm = AsyncMock()
        
        async def mock_ainvoke(prompt):
            from tilellm.modules.raptor.models.models import RaptorTraversalDecision
            return RaptorTraversalDecision(
                current_level=2,
                action="stop",
                reasoning="Test decision",
            )
        
        mock_structured_llm.ainvoke = mock_ainvoke
        mock_llm.with_structured_output = MagicMock(return_value=mock_structured_llm)
        
        result = await retriever.retrieve(
            request=request,
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
        )
        
        assert result.success is True
        assert result.strategy_used == "tree_traversal"


# ---------------------------------------------------------------------------
# Test Integration
# ---------------------------------------------------------------------------

class TestIntegration:
    """Integration tests."""
    
    @pytest.mark.asyncio
    async def test_end_to_end_raptor_workflow(
        self,
        sample_chunks,
        mock_llm,
        mock_embeddings,
        mock_vector_repo,
        mock_redis,
    ):
        """Test complete RAPTOR workflow."""
        # Build tree
        repo = RaptorRepository(redis_client=mock_redis)
        service = RaptorService(repo=repo)
        
        config = RaptorConfig(cluster_size=5, max_levels=2)
        
        build_response = await service.build_raptor_tree(
            chunks=sample_chunks,
            namespace="test-ns",
            doc_id="test_doc",
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
            config=config,
        )
        
        assert build_response.success is True
        
        # Retrieve
        retriever = RaptorRetriever(repo=repo)
        
        retrieval_request = RaptorRetrievalRequest(
            question="What is discussed?",
            namespace="test-ns",
            doc_id="test_doc",
            strategy=RaptorRetrievalStrategy.COLLAPSED_TREE,
        )
        
        retrieval_result = await retriever.retrieve(
            request=retrieval_request,
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
        )
        
        assert retrieval_result.success is True
        assert len(retrieval_result.results) > 0


# ---------------------------------------------------------------------------
# Test LangGraph Workflow
# ---------------------------------------------------------------------------

class TestLangGraphWorkflow:
    """Test LangGraph workflow."""
    
    @pytest.mark.asyncio
    async def test_create_summary_agent_workflow(
        self,
        mock_llm,
        mock_embeddings,
        mock_vector_repo,
        mock_redis,
    ):
        """Test creating summary agent workflow."""
        from tilellm.modules.raptor.agents import create_summary_agent_workflow
        
        repo = RaptorRepository(redis_client=mock_redis)
        
        workflow = create_summary_agent_workflow(
            repo=repo,
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
        )
        
        assert workflow is not None
    
    @pytest.mark.asyncio
    async def test_run_raptor_summarization(
        self,
        sample_chunks,
        mock_llm,
        mock_embeddings,
        mock_vector_repo,
        mock_redis,
    ):
        """Test running RAPTOR summarization."""
        from tilellm.modules.raptor.agents import run_raptor_summarization
        
        # Convert Document to dict format expected by workflow
        chunks_data = [
            {
                "content": chunk.page_content,
                "metadata": chunk.metadata,
            }
            for chunk in sample_chunks
        ]
        
        result = await run_raptor_summarization(
            chunks=chunks_data,
            namespace="test-ns",
            doc_id="test_doc",
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo,
            repo=RaptorRepository(redis_client=mock_redis),
            cluster_size=5,
            max_levels=2,
        )
        
        assert result["success"] is True
        assert result.get("tree_id") is not None


# ---------------------------------------------------------------------------
# Test Hybrid Search (Dense + Sparse)
# ---------------------------------------------------------------------------

class TestHybridSearch:
    """Test hybrid search with sparse vectors."""
    
    @pytest.mark.asyncio
    async def test_build_tree_with_sparse(
        self,
        sample_chunks,
        mock_llm,
        mock_embeddings,
        mock_sparse_encoder,
        mock_vector_repo_with_hybrid,
        mock_redis,
    ):
        """Test building RAPTOR tree with sparse vectors."""
        repo = RaptorRepository(redis_client=mock_redis)
        service = RaptorService(repo=repo)
        
        config = RaptorConfig(cluster_size=5, max_levels=2)
        
        response = await service.build_raptor_tree(
            chunks=sample_chunks,
            namespace="test-ns",
            doc_id="test_doc",
            llm=mock_llm,
            embeddings=mock_embeddings,
            vector_repo=mock_vector_repo_with_hybrid,
            config=config,
            sparse_encoder=mock_sparse_encoder,
        )
        
        assert response.success is True
        assert response.tree_id is not None
    
    def test_raptor_retrieval_request_hybrid(self):
        """Test RaptorRetrievalRequest with hybrid search."""
        from tilellm.modules.raptor.models.models import RaptorRetrievalRequest
        
        request = RaptorRetrievalRequest(
            question="What is this?",
            namespace="test-ns",
            use_hybrid=True,
            alpha=0.7,
            sparse_encoder="splade",
        )
        
        assert request.use_hybrid is True
        assert request.alpha == 0.7
        assert request.sparse_encoder == "splade"
    
    def test_raptor_node_sparse_embedding_ref(self):
        """Test RaptorNode with sparse embedding reference."""
        from tilellm.modules.raptor.models.models import RaptorNode, RaptorLevel
        
        node = RaptorNode(
            node_id="test_node",
            level=RaptorLevel.LEVEL_1,
            content="Test content",
            sparse_embedding_ref="sparse_emb_123",
        )
        
        assert node.sparse_embedding_ref == "sparse_emb_123"
    
    @pytest.mark.asyncio
    async def test_generate_sparse_embedding(
        self,
        mock_sparse_encoder,
    ):
        """Test sparse embedding generation."""
        repo = RaptorRepository()
        service = RaptorService(repo=repo)
        
        sparse_vector = await service._generate_sparse_embedding(
            text="Test query for sparse encoding",
            sparse_encoder=mock_sparse_encoder,
        )
        
        assert sparse_vector is not None
        assert "indices" in sparse_vector
        assert "values" in sparse_vector
        assert len(sparse_vector["indices"]) > 0
        assert len(sparse_vector["values"]) > 0
